CFLAGS=-Wall -Wextra -g

all:
	make ex1
	make ex4
	make ex5
	make ex6
	make ex9
	make ex10
	make ex11
	make ex16
	make ex16extra

clean:
	rm -f ex1
	rm -f ex4
	rm -f ex5
	rm -f ex6
	rm -f ex9
	rm -f ex10
	rm -f ex11
	rm -f ex16
	rm -f ex16extra

